#Server
server.port=8082
spring.application.name=transaction-recording-service

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:transactiondb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

#Trader Profile Service URL
# Used to verify trader exists before recording a transaction
kasibidge.trader-profile.base-url=http://localhost:8081