# ── Server ──────────────────────────────────────
server.port=8081
spring.application.name=trader-profile-service

spring.datasource.url=jdbc:postgresql://localhost:5432/kasibridge_traders
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=@pass123

# ── JPA ──────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── Actuator ─────────────────────────────────────
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always